-- 소리블룸 테이블 (Supabase → SQL Editor 에 붙여넣고 실행)
create table if not exists soribloom_child (
  code       text primary key,             -- 6자리 아동 코드(링크에 포함)
  data       jsonb not null default '{}',  -- {code,nick,pairs[],n,retry,showText,showJamo,created,updated}
  updated_at timestamptz not null default now()
);
alter table soribloom_child enable row level security;
create policy "sbc read"   on soribloom_child for select using (true);
create policy "sbc insert" on soribloom_child for insert with check (true);
create policy "sbc update" on soribloom_child for update using (true) with check (true);
create policy "sbc delete" on soribloom_child for delete using (true);

create table if not exists soribloom_result (
  id   bigint generated by default as identity primary key,
  code text not null,
  at   timestamptz not null default now(),
  data jsonb not null default '{}'         -- {code,nick,at,n,first,second,pct,items[],byPair{}}
);
create index if not exists soribloom_result_code_at on soribloom_result (code, at desc);
alter table soribloom_result enable row level security;
create policy "sbr read"   on soribloom_result for select using (true);
create policy "sbr insert" on soribloom_result for insert with check (true);
